### ISSUE TITLE
Undefined variable in parse_etc_password.yml

### ISSUE THREAD

**Issue by adds68** [ansible-lockdown/RHEL8-CIS#146] opened 2021-11-02 18:05 UTC
**Describe the Issue**
Undefined variable in parse_etc_password.yml

`5:   - name: "PRELIM | {{ rhel8cis_passwd_tasks }} | Parse /etc/passwd"`

**Expected Behavior**
I suspect it should be "5.5.2 | 6.2.7 | 6.2.8 6.2.20"

**Actual Behavior**
{{ rhel8cis_passwd_tasks }}

related to #61

**Comment by uk-bolly** [comment] 2021-12-15 16:39
Hi @adds68 

Thank you for taking the time to raise this issue. Feedback can only help to improve the content that is delivered.
I can see this was previously resolved but missed one line in the control title. 

I will be adding this fix to the next release.

Thank you once again

uk-bolly

**Comment by uk-bolly** [comment] 2021-12-27 10:06
hi @adds68 

Thank you again for the feedback.
An update the latest devel branch has now been released and this should address the issues you have seen here.
Please feel free to close the issue is all is working as expected or feedback accordingly.

Thanks again

uk-bolly

**Closed** 2022-01-06 09:33 UTC
Labels: bug
