### ISSUE TITLE
Running in check mode fails on task 6.2.20

### ISSUE THREAD

**Issue by ChandlerSwift** [ansible-lockdown/RHEL8-CIS#141] opened 2021-10-13 17:12 UTC
**Describe the Issue**
Running in check mode fails on task 6.2.20

**Expected Behavior**
Task doesn't have a syntax error

**Actual Behavior**
```
chandler@localhost % ansible-playbook --limit $HOST test.yml -vv --check --tags rule_6.2.20

TASK [RHEL8-CIS : 6.2.20 | L1 | AUDIT | Ensure all users' home directories exist] ***************************************************
task path: /ansible/roles/RHEL8-CIS/tasks/section_6/cis_6.2.x.yml:468
fatal: [[host]]: FAILED! => {"msg": "The conditional check 'rhel_08_6_2_20_patch_audit.stdout \"| length > 0\"' failed. The error was: template error while templating string: expected token 'end of statement block', got 'string'. String: {% if rhel_08_6_2_20_patch_audit.stdout \"| length > 0\" %} True {% else %} False {% endif %}"}

PLAY RECAP **************************************************************************************************************************
[host]   : ok=17   changed=0    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0
```

**Control(s) Affected**
6.2.20

**Environment (please complete the following information):**
 - Host Python Version: 3.6.8
```
ansible-playbook 2.10.9.post0
  config file = /ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

**Comment by uk-bolly** [comment] 2021-12-16 08:59
Hi @ChandlerSwift 

Thank you for  taking the time to report issues with this project, it is only with feedback from the community we can improve.
Apologies for the delay is responding to get this resolved.
This is now is a new branch which contains many other fixes as well as some improvements and enhancements. We hope to get this approved this week into devel.

**Comment by uk-bolly** [comment] 2021-12-27 10:05
Hi @ChandlerSwift 

Thank you again for the feedback.
An update the latest devel branch has now been released and this should address the issues you have seen here.
Please feel free to close the issue is all is working as expected or feedback accordingly.

Thanks again

uk-bolly

**Comment by uk-bolly** [comment] 2022-01-04 09:38
Closing request as now in devel

**Closed by uk-bolly** 2022-01-04 09:38 UTC
Labels: bug
