### ISSUE TITLE
CIS Control 5.2.13 incorrect value

### ISSUE THREAD

**Issue by Zablove** [ansible-lockdown/RHEL8-CIS#139] opened 2021-10-08 11:34 UTC
**Issue**
CIS Control 5.2.13 "Ensure SSH Idle Timeout Interval is configured" states that "The recommended ClientAliveCountMax setting is 0". However after running the playbook, the interval is set to 3.

**Expected Behavior**
Value clientalivecountmax in /etc/ssh/sshd_config is set to 0

**Actual Behavior**
Value clientalivecountmax in /etc/ssh/sshd_config is set to 3

**Control(s) Affected**
5.2.13 Ensure SSH Idle Timeout Interval is configured

**Environment:**
- Ansible Version: 2.10.8
- Host Python Version: 3.9.2
- Ansible Server Python Version: 3.9.2

**Possible Solution**
Change the file defaults/main.yml section rhel8cis_sshd parameter clientalivecountmax to 0.

**Comment by georgenalen** [comment] 2021-10-08 18:54
@Zablove,
 Thanks for finding this one, that is indeed a mistake. I will add those in the next release which should be soon. In the mean time those variables in defaults/main. You can override those settings by using extra vars and there are two related to that control. Both need the values updated, so use the vars below instead. I will keep this open until it makes it into the release version.

rhel8cis_sshd:
    clientalivecountmax: 0
    clientaliveinterval: 900

**Comment by uk-bolly** [comment] 2021-12-27 10:05
hi @Zablove 

Thank you again for the feedback.
An update the latest devel branch has now been released and this should address the issues you have seen here.
Please feel free to close the issue is all is working as expected  or feedback accordingly.

Thanks again

uk-bolly

**Closed** 2022-01-06 09:33 UTC
Labels: bug
