### ISSUE TITLE
Section 6.2.8: file does not have argument warn

### ISSUE THREAD

**Issue by areh** [ansible-lockdown/RHEL8-CIS#147] opened 2021-11-12 11:20 UTC
**Describe the Issue**
In section 6.2.8 there is a file statement to ensure owner of home folder is the user. This fails since warn is not an argument for file.

**Expected Behavior**
Without args/warn this works as expected

**Actual Behavior**
With args/warn this fails

**Control(s) Affected**
Role may not be implemented fully.

**Environment (please complete the following information):**
 - Ansible Version: 2.9.27
 - Host Python Version: 3.6.8
 - Ansible Server Python Version: 3.6.8
 - Additional Details:

**Additional Notes**

**Possible Solution**
Remove the following:
```
args:
  warn: no
```

**Comment by uk-bolly** [comment] 2021-12-27 10:06
hi @areh 

Thank you again for the feedback.
An update the latest devel branch has now been released and this should address the issues you have seen here.
Please feel free to close the issue is all is working as expected or feedback accordingly.

Thanks again

uk-bolly

**Closed** 2022-01-06 09:33 UTC
Labels: bug
