### ISSUE TITLE
Check mode labels missing

### ISSUE THREAD

**Issue by ChandlerSwift** [ansible-lockdown/RHEL8-CIS#143] opened 2021-10-13 17:49 UTC
**Describe the Issue**
Check mode runs fail on 1.1.15 (which also includes 1.1.16 and 1.1.17), and 4.2.1.4

**Expected Behavior**
Tasks run successfully in check mode

**Actual Behavior**
```
[...]
TASK [RHEL8-CIS : "1.1.15 | L1 | AUDIT | Ensure nodev option set on /dev/shm partition | Check for /dev/shm existence
 1.1.16 | L1 | AUDIT | Ensure nosuid option set on /dev/shm partition | Check for /dev/shm existence
 1.1.17 | L1 | AUDIT | Ensure noexec option set on /dev/shm partition | Check for /dev/shm existence"] ***
task path: /ansible/roles/RHEL8-CIS/tasks/section_1/cis_1.1.x.yml:250
skipping: [[host]] => {"changed": false, "msg": "skipped, running in check mode"}

TASK [RHEL8-CIS : "1.1.15 | L1 | PATCH | Ensure nodev option set on /dev/shm partition | skips if mount absent
 1.1.16 | L1 | PATCH | Ensure nosuid option set on /dev/shm partition | skips if mount absent
 1.1.17 | L1 | PATCH | Ensure noexec option set on /dev/shm partition | skips if mount absent"] ***
task path: /ansible/roles/RHEL8-CIS/tasks/section_1/cis_1.1.x.yml:259
fatal: [[host]]: FAILED! => {"msg": "The conditional check ''dev/shm' in rhel8cis_1_1_15_dev_shm_status.stdout' failed. The error was: error while evaluating conditional ('dev/shm' in rhel8cis_1_1_15_dev_shm_status.stdout): 'dict object' has no attribute 'stdout'\n\nThe error appears to be in '/ansible/roles/RHEL8-CIS/tasks/section_1/cis_1.1.x.yml': line 259, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n      - name: |\n        ^ here\n"}

PLAY RECAP *********************************************************************
[host]   : ok=16   changed=0    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0
```

**Control(s) Affected**
1.1.15/16/17, 4.2.1.4

**Environment (please complete the following information):**
 - Host Python Version: 3.6.8
```
ansible-playbook 2.10.9.post0
  config file = /ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

**Comment by uk-bolly** [comment] 2021-12-16 09:01
Hi @ChandlerSwift 

Again thank you for taking the time to report issues and provide feedback to this project.
This should now be incorporated to a new branch and hopefully will be approved and pulled into devel later this week.

regards

uk-bolly

**Comment by uk-bolly** [comment] 2021-12-27 10:05
hi @ChandlerSwift 

Thank you again for the feedback.
An update the latest devel branch has now been released and this should address the issues you have seen here.
Please feel free to close the issue is all is working as expected or feedback accordingly.

Thanks again

uk-bolly

**Comment by uk-bolly** [comment] 2022-01-04 09:38
Closing request as now in devel

**Closed by uk-bolly** 2022-01-04 09:38 UTC
Labels: bug
